install_neovim_mac:
	#brew install libintl
	brew install gettext
	wget https://github.com/neovim/neovim/releases/latest/download/nvim-macos.tar.gz
	xattr -c ./nvim-macos.tar.gz
	tar xzvf nvim-macos.tar.gz
	./nvim-macos/bin/nvim
