name: Dotfiles Installation Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-installation:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Run Installation Script
      run: make install

    - name: Check zsh configuration 
      run: |
        test -f "$HOME/.zshrc" || (echo "Zsh configuration dont exist" && exit 1)
        test -d "$HOME/.oh-my-zsh" || (echo "Oh My Zsh is not installed" && exit 1)

    - name: Check for Neovim configuration
      run: |9
        test -f "$HOME/.config/nvim/init.lua" || (echo "Neovim configuration dont exist" && exit 1)
        test -d "$HOME/.config/nvim/lua/custom" || (echo "Neovim plugins dont exist" && exit 1)

    - name: Check for Tmux configuration
      run: | 
        test -f "$HOME/.tmux/plugins/tpm/tpm" || (echo "Tmux plugins dont exist" && exit 1)
        test -f "$HOME/.tmux.conf" || (echo "Tmux configuration dont exists" && exit 1)

