name: Dotfiles Installation Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-installation:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Run Installation Script
      run: make install

    - name: Check if Oh My Zsh is installed
      run: test -d "$HOME/.oh-my-zsh" && echo "Oh My Zsh is installed" || exit 1

    - name: Check for Neovim configuration
      run: test -f "$HOME/.config/nvim/init.vim" && echo "Neovim configuration exists" || exit 1
    - name: Check custom neovim plugins
      run: test -d "$HOME/.config/nvim/luat/custom" && echo "Neovim plugins exist" || exit 1

    - name: Check for Tmux configuration
      run: test -f "$HOME/.tmux.conf" && echo "Tmux configuration exists" || exit 1

    - name: Check for Zsh configuration
      run: test -f "$HOME/.zshrc" && echo "Zsh configuration exists" || exit 1 
